apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: replika-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: replika-manager-role
subjects:
- kind: ServiceAccount
  name: replika-controller-manager
  namespace: replika-system

