apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole-replika-manager-role.yaml
- clusterrolebinding-replika-manager-rolebinding.yaml
- configmap-replika-manager-config.yaml
- customresourcedefinition-replikas.replika.prosimcorp.com.yaml
- deployment-replika-controller-manager.yaml
- namespace-replika.yaml
- role-replika-leader-election-role.yaml
- rolebinding-replika-leader-election-rolebinding.yaml
- serviceaccount-replika-controller-manager.yaml
