apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replika-leader-election-rolebinding
  namespace: replika-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: replika-leader-election-role
subjects:
- kind: ServiceAccount
  name: replika-controller-manager
  namespace: replika-system

