# permissions for end users to view replikas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replika-viewer-role
rules:
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas/status
  verbs:
  - get
