# permissions for end users to view replikas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replika-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: replika
    app.kubernetes.io/part-of: replika
    app.kubernetes.io/managed-by: kustomize
  name: replika-viewer-role
rules:
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas/status
  verbs:
  - get
