apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole/replika2-manager-role.yaml
- clusterrole/replika2-metrics-reader.yaml
- clusterrole/replika2-proxy-role.yaml
- clusterrolebinding/replika2-manager-rolebinding.yaml
- clusterrolebinding/replika2-proxy-rolebinding.yaml
- configmap/replika2-manager-config.yaml
- customresourcedefinition/replikas-replika-prosimcorp-com.yaml
- deployment/replika2-controller-manager.yaml
- namespace/replika2-system.yaml
- role/replika2-leader-election-role.yaml
- rolebinding/replika2-leader-election-rolebinding.yaml
- service/replika2-controller-manager-metrics-service.yaml
- serviceaccount/replika2-controller-manager.yaml
