apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: replika
    control-plane: replika
  name: replika-controller-manager-metrics-service
  namespace: replika
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: replika
    control-plane: replika

