//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Replika) DeepCopyInto(out *Replika) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Replika.
func (in *Replika) DeepCopy() *Replika {
	if in == nil {
		return nil
	}
	out := new(Replika)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Replika) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplikaList) DeepCopyInto(out *ReplikaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Replika, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplikaList.
func (in *ReplikaList) DeepCopy() *ReplikaList {
	if in == nil {
		return nil
	}
	out := new(ReplikaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReplikaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplikaSourceSpec) DeepCopyInto(out *ReplikaSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplikaSourceSpec.
func (in *ReplikaSourceSpec) DeepCopy() *ReplikaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(ReplikaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplikaSpec) DeepCopyInto(out *ReplikaSpec) {
	*out = *in
	out.Synchronization = in.Synchronization
	out.Source = in.Source
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplikaSpec.
func (in *ReplikaSpec) DeepCopy() *ReplikaSpec {
	if in == nil {
		return nil
	}
	out := new(ReplikaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplikaStatus) DeepCopyInto(out *ReplikaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplikaStatus.
func (in *ReplikaStatus) DeepCopy() *ReplikaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplikaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplikaTargetNamespacesSpec) DeepCopyInto(out *ReplikaTargetNamespacesSpec) {
	*out = *in
	if in.ReplicateIn != nil {
		in, out := &in.ReplicateIn, &out.ReplicateIn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeFrom != nil {
		in, out := &in.ExcludeFrom, &out.ExcludeFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplikaTargetNamespacesSpec.
func (in *ReplikaTargetNamespacesSpec) DeepCopy() *ReplikaTargetNamespacesSpec {
	if in == nil {
		return nil
	}
	out := new(ReplikaTargetNamespacesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplikaTargetSpec) DeepCopyInto(out *ReplikaTargetSpec) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplikaTargetSpec.
func (in *ReplikaTargetSpec) DeepCopy() *ReplikaTargetSpec {
	if in == nil {
		return nil
	}
	out := new(ReplikaTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizationSpec) DeepCopyInto(out *SynchronizationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizationSpec.
func (in *SynchronizationSpec) DeepCopy() *SynchronizationSpec {
	if in == nil {
		return nil
	}
	out := new(SynchronizationSpec)
	in.DeepCopyInto(out)
	return out
}
