{{- if .Values.customResourceDefinitions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "replika.fullname" . }}-custom-clusterrolebinding
  labels:
    {{- include "replika.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "replika.fullname" . }}-custom-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "replika.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
