apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: replika-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas/finalizers
  verbs:
  - update
- apiGroups:
  - replika.prosimcorp.com
  resources:
  - replikas/status
  verbs:
  - get
  - patch
  - update

