apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: replika
  name: replika-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get

