apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: replika
  name: replika-leader-election-rolebinding
  namespace: replika
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: replika-leader-election-role
subjects:
- kind: ServiceAccount
  name: replika-controller-manager
  namespace: replika

